### ISSUE TITLE
Select simple type value from db

### ISSUE THREAD

**Issue by dimparf** [dimparf/Soriento#27]
`db.asyncQueryBySql[String]("select name from User")` is not working.
scala.ScalaReflectionException: constructor String encapsulates multiple overloaded alternatives and cannot be treated as a method. Consider invoking `<offending symbol>.asTerm.alternatives` and manually picking the required method
    at scala.reflect.api.Symbols$SymbolApi$class.asMethod(Symbols.scala:228)
    at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:84)
    at com.emotioncity.soriento.ReflectionUtils$.constructor(ReflectionUtils.scala:28)
    at com.emotioncity.soriento.loadbyname.DocumentFromConstructor.<init>(ClassNameReadersRegistry.scala:36)

**Comment by allComputableThings** [comment]
I probably introduced this bug.
Is there a test case for it?

**Comment by allComputableThings** [comment]
Never mind -- i'll add one.
